// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_Luis_Miguel_Caceres.Server.DAL;

#nullable disable

namespace Parcial2_Luis_Miguel_Caceres.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230712032423_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Parcial2_Luis_Miguel_Caceres.Shared.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantiadadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("PesoTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Caceres.Shared.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CantidadUtilizada")
                        .HasColumnType("REAL");

                    b.Property<int?>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Caceres.Shared.Models.Frutos", b =>
                {
                    b.Property<int>("FrutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Disponibilidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("FrutoId");

                    b.ToTable("Frutos");

                    b.HasData(
                        new
                        {
                            FrutoId = 1,
                            Disponibilidad = 50,
                            Nombre = "Maní"
                        },
                        new
                        {
                            FrutoId = 2,
                            Disponibilidad = 600,
                            Nombre = "Pistachos"
                        },
                        new
                        {
                            FrutoId = 3,
                            Disponibilidad = 500,
                            Nombre = "Pasas"
                        },
                        new
                        {
                            FrutoId = 4,
                            Disponibilidad = 700,
                            Nombre = "Ciruelas"
                        });
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Caceres.Shared.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CantidadUtilizada")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Caceres.Shared.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Parcial2_Luis_Miguel_Caceres.Shared.Entradas", null)
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("EntradaId");
                });

            modelBuilder.Entity("Parcial2_Luis_Miguel_Caceres.Shared.Entradas", b =>
                {
                    b.Navigation("EntradasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
